on:
  release:
    types: [created]
  workflow_dispatch:
  
name: Build docker image
jobs:
  build:
    name: KernelCI Storage Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push
# running ARM64 will take a long time (1hr+), so we only build for AMD64 for now
#        run: |
#         docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/nuclearcat/kernelci-storage:latest --push .
        run: |
         docker buildx build --platform linux/amd64 -t ghcr.io/nuclearcat/kernelci-storage:latest --push .
      

